import '../models/product.dart';
import '../models/category.dart';
import '../models/customer.dart';
import '../models/supplier.dart';
import '../models/user.dart';
import '../models/expense.dart';
import '../models/shop_settings.dart';

class SeedData {
  static ShopSettings defaultSettings = ShopSettings();

  static List<Category> defaultCategories = [
    Category(id: 'cat-1', name: 'Cement', description: 'Portland & blended cement bags'),
    Category(id: 'cat-2', name: 'Sand & Gravel', description: 'River sand, metal, aggregates'),
    Category(id: 'cat-3', name: 'Bricks & Blocks', description: 'Red bricks, cement blocks'),
    Category(id: 'cat-4', name: 'Paint & Accessories', description: 'Wall paints, primer, brushes, rollers'),
    Category(id: 'cat-5', name: 'Plumbing', description: 'PVC pipes, fittings, valves, taps'),
    Category(id: 'cat-6', name: 'Electrical', description: 'Wires, switches, sockets, breakers'),
    Category(id: 'cat-7', name: 'Hand Tools', description: 'Hammers, pliers, tape measures, saws'),
    Category(id: 'cat-8', name: 'Power Tools', description: 'Drills, grinders, cutters, power saws'),
    Category(id: 'cat-9', name: 'Nails & Screws', description: 'Wire nails, wood screws, bolts'),
    Category(id: 'cat-10', name: 'Roofing', description: 'Zinc-alum sheets, roofing tiles'),
    Category(id: 'cat-11', name: 'Hardware & Adhesives', description: 'Glue, silicone, padlocks, hinges'),
    Category(id: 'cat-12', name: 'Building Materials', description: 'Reinforcement steel, mesh, plaster'),
    Category(id: 'cat-13', name: 'Safety Equipment', description: 'Helmets, gloves, safety boots'),
    Category(id: 'cat-14', name: 'Garden Tools', description: 'Shovels, rakes, hoses'),
  ];

  static List<User> defaultUsers = [
    User(
      id: 'usr-1',
      username: 'admin',
      name: 'Hardware Owner',
      role: 'Admin',
      pinOrPassword: '1234',
      permissions: ['all'],
    ),
    User(
      id: 'usr-2',
      username: 'cashier',
      name: 'Cashier 01',
      role: 'Cashier',
      pinOrPassword: '1234',
      permissions: ['create_sale', 'view_sales', 'print_invoice', 'customer_payment'],
    ),
    User(
      id: 'usr-3',
      username: 'store',
      name: 'Store Keeper',
      role: 'Store Keeper',
      pinOrPassword: '1234',
      permissions: ['view_inventory', 'stock_adjustment', 'purchases', 'deliveries'],
    ),
    User(
      id: 'usr-4',
      username: 'driver',
      name: 'Delivery Staff',
      role: 'Delivery Staff',
      pinOrPassword: '1234',
      permissions: ['view_deliveries', 'update_delivery'],
    ),
  ];

  static List<Supplier> defaultSuppliers = [
    Supplier(
      id: 'sup-1',
      code: 'SUP-001',
      name: 'Tokyo Cement PLC',
      company: 'Tokyo Cement Co. Lanka PLC',
      phone: '0112111111',
      email: 'sales@tokyocement.lk',
      address: 'No 12, Sri Chittampalam A Gardiner Mawatha, Colombo',
      taxVatNo: 'VAT-998811',
      balance: 78000.0,
      creditLimit: 1000000.0,
    ),
    Supplier(
      id: 'sup-2',
      code: 'SUP-002',
      name: 'S-Lon Lanka Ltd',
      company: 'S-Lon Lanka Private Limited',
      phone: '0112222222',
      email: 'info@slon.lk',
      address: 'Sir Baron Jayathilaka Mawatha, Colombo 01',
      taxVatNo: 'VAT-445566',
      balance: 0.0,
      creditLimit: 500000.0,
    ),
    Supplier(
      id: 'sup-3',
      code: 'SUP-003',
      name: 'Asian Paints Lanka',
      company: 'Asian Paints (Lanka) Ltd',
      phone: '0112333333',
      email: 'orders@asianpaints.lk',
      address: 'Industrial Estate, Ekala, Ja-Ela',
      taxVatNo: 'VAT-112233',
      balance: 150000.0,
      creditLimit: 750000.0,
    ),
    Supplier(
      id: 'sup-4',
      code: 'SUP-004',
      name: 'Bosch Lanka Tools',
      company: 'Robert Bosch Lanka Ltd',
      phone: '0112444444',
      email: 'service@bosch.lk',
      address: 'Union Place, Colombo 02',
      taxVatNo: 'VAT-778899',
      balance: 0.0,
      creditLimit: 500000.0,
    ),
  ];

  static List<Customer> defaultCustomers = [
    Customer(
      id: 'cust-0',
      code: 'CUST-000',
      name: 'Walk-in Customer',
      phone: 'N/A',
      customerType: 'Walk-in',
      creditLimit: 0.0,
      balance: 0.0,
    ),
    Customer(
      id: 'cust-1',
      code: 'CUST-001',
      name: 'Perera Builders',
      phone: '0771234567',
      email: 'perera.build@gmail.com',
      address: 'No 100, Galle Road, Dehiwala',
      customerType: 'Contractor',
      creditLimit: 300000.0,
      balance: 45000.0,
      notes: 'Privileged commercial contractor',
    ),
    Customer(
      id: 'cust-2',
      code: 'CUST-002',
      name: 'Silva Engineers & Construction',
      phone: '0719876543',
      email: 'silva.eng@hotmail.com',
      address: 'No 25, Kandy Road, Kadawatha',
      customerType: 'Company',
      creditLimit: 500000.0,
      balance: 125000.0,
    ),
    Customer(
      id: 'cust-3',
      code: 'CUST-003',
      name: 'Kamal Wickramasinghe',
      phone: '0755554433',
      address: 'No 14, Station Road, Kelaniya',
      customerType: 'Regular',
      creditLimit: 50000.0,
      balance: 12000.0,
    ),
  ];

  static List<Product> defaultProducts = [
    Product(
      id: 'prod-1',
      code: 'PRD-001',
      name: 'Tokyo Super Cement 50kg',
      category: 'Cement',
      brand: 'Tokyo Super',
      unit: 'Bag',
      purchasePrice: 2850.0,
      sellingPrice: 3050.0,
      wholesalePrice: 2950.0,
      currentStock: 120.0,
      minStock: 30.0,
      reorderLevel: 40.0,
      supplierId: 'sup-1',
      supplierName: 'Tokyo Cement PLC',
      rackLocation: 'Rack A-01',
    ),
    Product(
      id: 'prod-2',
      code: 'PRD-002',
      name: 'PVC Pipe 1/2" (Type 600)',
      category: 'Plumbing',
      brand: 'S-Lon',
      unit: 'Feet',
      purchasePrice: 150.0,
      sellingPrice: 220.0,
      wholesalePrice: 195.0,
      currentStock: 850.0,
      minStock: 100.0,
      reorderLevel: 200.0,
      supplierId: 'sup-2',
      supplierName: 'S-Lon Lanka Ltd',
      rackLocation: 'Rack P-04',
    ),
    Product(
      id: 'prod-3',
      code: 'PRD-003',
      name: 'Asian Paints Apex Exterior White 10L',
      category: 'Paint & Accessories',
      brand: 'Asian Paints',
      unit: 'Liter',
      purchasePrice: 12000.0,
      sellingPrice: 14500.0,
      wholesalePrice: 13800.0,
      currentStock: 14.0,
      minStock: 20.0,
      reorderLevel: 25.0,
      supplierId: 'sup-3',
      supplierName: 'Asian Paints Lanka',
      rackLocation: 'Rack C-02',
    ),
    Product(
      id: 'prod-4',
      code: 'PRD-004',
      name: 'Washed River Sand',
      category: 'Sand & Gravel',
      brand: 'Local',
      unit: 'Cubic Feet',
      purchasePrice: 350.0,
      sellingPrice: 450.0,
      wholesalePrice: 400.0,
      currentStock: 500.0,
      minStock: 100.0,
      reorderLevel: 150.0,
      rackLocation: 'Yard Area B',
    ),
    Product(
      id: 'prod-5',
      code: 'PRD-005',
      name: 'Red Clay Wire-Cut Bricks',
      category: 'Bricks & Blocks',
      brand: 'Local',
      unit: 'Piece',
      purchasePrice: 32.0,
      sellingPrice: 45.0,
      wholesalePrice: 40.0,
      currentStock: 4500.0,
      minStock: 1000.0,
      reorderLevel: 1500.0,
      rackLocation: 'Yard Area A',
    ),
    Product(
      id: 'prod-6',
      code: 'PRD-006',
      name: 'Bosch GWS 750-100 Angle Grinder 4"',
      category: 'Power Tools',
      brand: 'Bosch',
      unit: 'Piece',
      purchasePrice: 15000.0,
      sellingPrice: 18500.0,
      wholesalePrice: 17500.0,
      currentStock: 12.0,
      minStock: 5.0,
      reorderLevel: 8.0,
      supplierId: 'sup-4',
      supplierName: 'Bosch Lanka Tools',
      rackLocation: 'Rack T-01',
      warrantyMonths: 12,
    ),
    Product(
      id: 'prod-7',
      code: 'PRD-007',
      name: 'S-Lon PVC Elbow 1/2"',
      category: 'Plumbing',
      brand: 'S-Lon',
      unit: 'Piece',
      purchasePrice: 55.0,
      sellingPrice: 85.0,
      wholesalePrice: 70.0,
      currentStock: 240.0,
      minStock: 50.0,
      reorderLevel: 80.0,
      supplierId: 'sup-2',
      supplierName: 'S-Lon Lanka Ltd',
      rackLocation: 'Rack P-02',
    ),
    Product(
      id: 'prod-8',
      code: 'PRD-008',
      name: 'Zinc-Alum Roofing Sheet 8ft',
      category: 'Roofing',
      brand: 'Lysaght',
      unit: 'Piece',
      purchasePrice: 2700.0,
      sellingPrice: 3200.0,
      wholesalePrice: 3000.0,
      currentStock: 75.0,
      minStock: 20.0,
      reorderLevel: 30.0,
      rackLocation: 'Storage Shed',
    ),
    Product(
      id: 'prod-9',
      code: 'PRD-009',
      name: 'Steel Wire Nails 2"',
      category: 'Nails & Screws',
      brand: 'Generic',
      unit: 'Kg',
      purchasePrice: 310.0,
      sellingPrice: 420.0,
      wholesalePrice: 380.0,
      currentStock: 65.0,
      minStock: 20.0,
      reorderLevel: 30.0,
      rackLocation: 'Rack N-01',
    ),
    Product(
      id: 'prod-10',
      code: 'PRD-010',
      name: 'S-Lon PVC Solvent Cement 100g',
      category: 'Hardware & Adhesives',
      brand: 'S-Lon',
      unit: 'Box',
      purchasePrice: 240.0,
      sellingPrice: 350.0,
      wholesalePrice: 300.0,
      currentStock: 15.0,
      minStock: 25.0,
      reorderLevel: 30.0,
      supplierId: 'sup-2',
      supplierName: 'S-Lon Lanka Ltd',
      rackLocation: 'Rack H-03',
    ),
  ];

  static List<ExpenseCategory> defaultExpenseCategories = [
    ExpenseCategory(id: 'expcat-1', name: 'Transport'),
    ExpenseCategory(id: 'expcat-2', name: 'Electricity'),
    ExpenseCategory(id: 'expcat-3', name: 'Water'),
    ExpenseCategory(id: 'expcat-4', name: 'Rent'),
    ExpenseCategory(id: 'expcat-5', name: 'Salary'),
    ExpenseCategory(id: 'expcat-6', name: 'Fuel'),
    ExpenseCategory(id: 'expcat-7', name: 'Maintenance'),
    ExpenseCategory(id: 'expcat-8', name: 'Delivery Charge'),
    ExpenseCategory(id: 'expcat-9', name: 'Telephone & Internet'),
    ExpenseCategory(id: 'expcat-10', name: 'Stationery'),
    ExpenseCategory(id: 'expcat-11', name: 'Other'),
  ];
}
